[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:lingproxy-backend]
command=/app/lingproxy
directory=/app
user=lingproxy
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/lingproxy-backend.err.log
stdout_logfile=/var/log/supervisor/lingproxy-backend.out.log
environment=GIN_MODE="release",TZ="Asia/Shanghai"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
